/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package urm;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextPane;
import javax.swing.JViewport;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author muatsoft
 */
public class MaqURM extends javax.swing.JFrame {

    private AnaliseSintatica analSint;
    private Interpretador interpreta;
    private String codigoFonte = Constantes.testos[2];
    private File ficheiro;
    TextLineNumber lineNumbers;
    private FileInputStream is;

    public JTable getTblRegistos() {
        return tblRegistos;
    }

    /**
     * Creates new form MaqURM
     *
     * @param v
     */
    public MaqURM(int v) {
    }

    public MaqURM() {
        initComponents();
        setTitle(Constantes.msg[11]);
        setLocationRelativeTo(null);
        lineNumbers = new TextLineNumber(txtCodigo, 2);
        painelTexto.setRowHeader(new JViewport());
        painelTexto.getRowHeader().add(lineNumbers);
        txtCodigo.setText(Constantes.template);
        valorExecucao.setText(Constantes.testos[0] + Constantes.testos[0] + tempoDeSimulacao.getValue());
        estencao.setText(Constantes.testos[12]);
        //System.err.println(tempoDeSimulacao.getValue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraFerramentas = new javax.swing.JToolBar();
        btNovo = new javax.swing.JButton();
        btAbrir = new javax.swing.JButton();
        btGuardarComo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btCopiar = new javax.swing.JButton();
        btCortar = new javax.swing.JButton();
        btColar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btSimular = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        tempoDeSimulacao = new javax.swing.JSlider();
        valorExecucao = new javax.swing.JLabel();
        estencao = new javax.swing.JLabel();
        divisaoCodigoResultado = new javax.swing.JSplitPane();
        painelTexto = new javax.swing.JScrollPane();
        divisaoTextTabela = new javax.swing.JSplitPane();
        ladoRegistos = new javax.swing.JScrollPane();
        tblRegistos = new javax.swing.JTable();
        ladoCodigo = new javax.swing.JScrollPane();
        txtCodigo = new javax.swing.JTextPane();
        verMensagens = new javax.swing.JScrollPane();
        txtMensagemConsola = new javax.swing.JEditorPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFincheiro = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        menuSimular = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem17 = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador URM");
        setIconImages(null);
        setLocationByPlatform(true);
        setName("MaqUrm"); // NOI18N

        barraFerramentas.setRollover(true);

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/document-new (2).png"))); // NOI18N
        btNovo.setToolTipText("nova simulação");
        btNovo.setFocusable(false);
        btNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        barraFerramentas.add(btNovo);

        btAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/document-open-4.png"))); // NOI18N
        btAbrir.setToolTipText("abrir");
        btAbrir.setFocusable(false);
        btAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirActionPerformed(evt);
            }
        });
        barraFerramentas.add(btAbrir);

        btGuardarComo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/document-export (2).png"))); // NOI18N
        btGuardarComo.setToolTipText("guardar");
        btGuardarComo.setFocusable(false);
        btGuardarComo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btGuardarComo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarComoActionPerformed(evt);
            }
        });
        barraFerramentas.add(btGuardarComo);
        barraFerramentas.add(jSeparator2);

        btCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit-copy-6.png"))); // NOI18N
        btCopiar.setToolTipText("copiar");
        btCopiar.setFocusable(false);
        btCopiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCopiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCopiarActionPerformed(evt);
            }
        });
        barraFerramentas.add(btCopiar);

        btCortar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit-cut-6.png"))); // NOI18N
        btCortar.setToolTipText("cortar");
        btCortar.setFocusable(false);
        btCortar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCortar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCortarActionPerformed(evt);
            }
        });
        barraFerramentas.add(btCortar);

        btColar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit-paste-3 (2).png"))); // NOI18N
        btColar.setToolTipText("colar");
        btColar.setFocusable(false);
        btColar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btColar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btColar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColarActionPerformed(evt);
            }
        });
        barraFerramentas.add(btColar);
        barraFerramentas.add(jSeparator3);

        btSimular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/media-playback-start-3 (2).png"))); // NOI18N
        btSimular.setToolTipText("simular");
        btSimular.setFocusable(false);
        btSimular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSimular.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimularActionPerformed(evt);
            }
        });
        barraFerramentas.add(btSimular);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/media-seek-forward-3 (2).png"))); // NOI18N
        jButton1.setToolTipText("simular passo à passo");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        barraFerramentas.add(jButton1);

        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit-clear-3 (2).png"))); // NOI18N
        btLimpar.setToolTipText("limpar tabela de resultados");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        barraFerramentas.add(btLimpar);
        barraFerramentas.add(jSeparator8);

        tempoDeSimulacao.setPaintLabels(true);
        tempoDeSimulacao.setPaintTicks(true);
        tempoDeSimulacao.setToolTipText("Velocidade da simulação");
        tempoDeSimulacao.setValue(0);
        tempoDeSimulacao.setMaximumSize(new java.awt.Dimension(100, 31));
        tempoDeSimulacao.setMinimumSize(new java.awt.Dimension(100, 31));
        tempoDeSimulacao.setPreferredSize(new java.awt.Dimension(100, 31));
        tempoDeSimulacao.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tempoDeSimulacaoStateChanged(evt);
            }
        });
        tempoDeSimulacao.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                tempoDeSimulacaoAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tempoDeSimulacaoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        barraFerramentas.add(tempoDeSimulacao);

        valorExecucao.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        valorExecucao.setForeground(new java.awt.Color(0, 153, 255));
        valorExecucao.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        barraFerramentas.add(valorExecucao);

        estencao.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        estencao.setForeground(new java.awt.Color(0, 153, 255));
        estencao.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        barraFerramentas.add(estencao);

        divisaoCodigoResultado.setDividerSize(4);
        divisaoCodigoResultado.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        painelTexto.setBorder(null);

        divisaoTextTabela.setDividerSize(4);
        divisaoTextTabela.setRequestFocusEnabled(false);
        divisaoTextTabela.setVerifyInputWhenFocusTarget(false);

        tblRegistos.setBackground(new java.awt.Color(241, 244, 255));
        tblRegistos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblRegistos.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        tblRegistos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)}
            },
            new String [] {
                "R 1", "R 2", "R 3", "R 4", "R 5", "R 6", "R 7", "R 8", "R 9", "R 10"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblRegistos.setToolTipText("Valores dos registos");
        tblRegistos.setEditingRow(1);
        tblRegistos.setFillsViewportHeight(true);
        tblRegistos.setGridColor(new java.awt.Color(204, 204, 204));
        tblRegistos.setIntercellSpacing(new java.awt.Dimension(10, 2));
        tblRegistos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblRegistos.getTableHeader().setResizingAllowed(false);
        tblRegistos.getTableHeader().setReorderingAllowed(false);
        tblRegistos.setUpdateSelectionOnSort(false);
        tblRegistos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblRegistosKeyReleased(evt);
            }
        });
        ladoRegistos.setViewportView(tblRegistos);

        divisaoTextTabela.setRightComponent(ladoRegistos);

        txtCodigo.setBackground(new java.awt.Color(241, 244, 255));
        txtCodigo.setBorder(null);
        txtCodigo.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(0, 51, 255));
        ladoCodigo.setViewportView(txtCodigo);

        divisaoTextTabela.setLeftComponent(ladoCodigo);

        painelTexto.setViewportView(divisaoTextTabela);

        divisaoCodigoResultado.setTopComponent(painelTexto);

        verMensagens.setBorder(javax.swing.BorderFactory.createTitledBorder("Mensagem"));
        verMensagens.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        verMensagens.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        verMensagens.setHorizontalScrollBar(null);
        verMensagens.setInheritsPopupMenu(true);

        txtMensagemConsola.setEditable(false);
        txtMensagemConsola.setBackground(new java.awt.Color(241, 239, 250));
        txtMensagemConsola.setForeground(Color.BLUE
        );
        txtMensagemConsola.setToolTipText("Mensagens e avisos");
        txtMensagemConsola.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtMensagemConsola.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        txtMensagemConsola.setEnabled(false);
        txtMensagemConsola.setRequestFocusEnabled(false);
        verMensagens.setViewportView(txtMensagemConsola);

        divisaoCodigoResultado.setBottomComponent(verMensagens);

        menuFincheiro.setText("Ficheiro");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/document-new.png"))); // NOI18N
        jMenuItem1.setText("Novo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuFincheiro.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/document-open-4_1.png"))); // NOI18N
        jMenuItem2.setText("Abrir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuFincheiro.add(jMenuItem2);
        menuFincheiro.add(jSeparator4);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/document-save-all.png"))); // NOI18N
        jMenuItem4.setText("Guardar como");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuFincheiro.add(jMenuItem4);
        menuFincheiro.add(jSeparator6);

        jMenuItem18.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/document-print.png"))); // NOI18N
        jMenuItem18.setText("Imprimir");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        menuFincheiro.add(jMenuItem18);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/application-exit.png"))); // NOI18N
        jMenuItem5.setText("Sair");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuFincheiro.add(jMenuItem5);

        jMenuBar1.add(menuFincheiro);

        menuEditar.setText("Editar");

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit-undo.png"))); // NOI18N
        jMenuItem16.setText("Anular");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        menuEditar.add(jMenuItem16);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit-redo.png"))); // NOI18N
        jMenuItem15.setText("Restaurar");
        menuEditar.add(jMenuItem15);
        menuEditar.add(jSeparator1);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit-copy-7.png"))); // NOI18N
        jMenuItem6.setText("Copiar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuEditar.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit-cut-7.png"))); // NOI18N
        jMenuItem7.setText("Cortar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menuEditar.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit-paste-3.png"))); // NOI18N
        jMenuItem8.setText("Colar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menuEditar.add(jMenuItem8);
        menuEditar.add(jSeparator5);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit-select-all-3.png"))); // NOI18N
        jMenuItem9.setText("Selecionar tudo");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        menuEditar.add(jMenuItem9);

        jMenuBar1.add(menuEditar);

        jMenu1.setText("Exemplos");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/dialog-accept.png"))); // NOI18N
        jMenuItem3.setText("Soma (x,y)");
        jMenu1.add(jMenuItem3);

        jMenuItem19.setText("Multiplo (x)");
        jMenu1.add(jMenuItem19);

        jMenuItem20.setText("Maior número (x,y)");
        jMenu1.add(jMenuItem20);

        jMenuBar1.add(jMenu1);

        menuSimular.setText("Simular");

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/run-build-3.png"))); // NOI18N
        jMenuItem10.setText("Compilar");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        menuSimular.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/media-playback-start-3.png"))); // NOI18N
        jMenuItem11.setText("Executar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        menuSimular.add(jMenuItem11);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/go-next-9.png"))); // NOI18N
        jMenuItem12.setText("Compilar & Executar");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        menuSimular.add(jMenuItem12);
        menuSimular.add(jSeparator7);

        jMenuItem17.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit-clear-3.png"))); // NOI18N
        jMenuItem17.setText("Limpar resultados");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        menuSimular.add(jMenuItem17);

        jMenuBar1.add(menuSimular);

        menuAjuda.setText("Ajuda");

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/help-2.png"))); // NOI18N
        jMenuItem13.setText("Programa");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        menuAjuda.add(jMenuItem13);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/help-about-3.png"))); // NOI18N
        jMenuItem14.setText("Programador");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        menuAjuda.add(jMenuItem14);

        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(divisaoCodigoResultado)
            .add(barraFerramentas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(barraFerramentas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(divisaoCodigoResultado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimularActionPerformed
        if (compilarCodigo()) {
            txtMensagemConsola.setBackground(Color.white);
            txtMensagemConsola.setForeground(Color.green);
            codigoFonte = txtCodigo.getText();
            executarCodigo(codigoFonte);
        } else {
            txtMensagemConsola.setBackground(Color.white);
            txtMensagemConsola.setForeground(Color.red);
        }
    }//GEN-LAST:event_btSimularActionPerformed

    private void tblRegistosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblRegistosKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblRegistosKeyReleased

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        novaSimulacao();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirActionPerformed
        // TODO add your handling code here:
        abrirSimulacao();
    }//GEN-LAST:event_btAbrirActionPerformed

    private void btCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCopiarActionPerformed
        // TODO add your handling code here:
        txtCodigo.copy();
    }//GEN-LAST:event_btCopiarActionPerformed

    private void btCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCortarActionPerformed
        // TODO add your handling code here:
        txtCodigo.cut();
    }//GEN-LAST:event_btCortarActionPerformed

    private void btColarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btColarActionPerformed
        // TODO add your handling code here:
        txtCodigo.paste();
    }//GEN-LAST:event_btColarActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        int confirma = JOptionPane.showConfirmDialog(null, Constantes.msg[6]);
        if (confirma == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        novaSimulacao();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        txtCodigo.copy();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        txtCodigo.cut();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        txtCodigo.paste();

    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        txtCodigo.selectAll();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        if (compilarCodigo()) {
            codigoFonte = txtCodigo.getText();
        } else {
            txtMensagemConsola.setBackground(Color.white);
            txtMensagemConsola.setForeground(Color.red);
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        txtMensagemConsola.setBackground(Color.white);
        txtMensagemConsola.setForeground(Color.green);
        executarCodigo(codigoFonte);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        if (compilarCodigo()) {
            txtMensagemConsola.setBackground(Color.white);
            txtMensagemConsola.setForeground(Color.green);
            codigoFonte = txtCodigo.getText();
            executarCodigo(codigoFonte);
        } else {
            txtMensagemConsola.setBackground(Color.white);
            txtMensagemConsola.setForeground(Color.red);
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        guardarComoSimulacao();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        abrirSimulacao();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarComoActionPerformed
        // TODO add your handling code here:
        guardarComoSimulacao();
    }//GEN-LAST:event_btGuardarComoActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        limparTabelaResultado();
    }//GEN-LAST:event_btLimparActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        limparTabelaResultado();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            interpreta = new Interpretador((DefaultTableModel) getTblRegistos().getModel());
            String partes[] = txtCodigo.getText().trim().toUpperCase().replaceAll(Constantes.testos[0], Constantes.testos[2]).split(Constantes.testos[1]);

            for (int contador = 0; contador < partes.length; contador++) {
                char c[] = partes[contador].toCharArray();
                if (!(partes[contador].isEmpty()) && !(c[0] == Constantes.instrucao[4])) {
                    // selecionar a linha e mudar a cor da mesma linha
                    contador = interpreta.passoApasso(partes[contador], contador);

                    if (JOptionPane.showConfirmDialog(null, Constantes.msg[9], Constantes.msg[10], JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                    } else {
                        break;
                    }
                } else {
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, Constantes.msg[8]);
        }
        pegaResultado();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        try {
            // TODO add your handling code here:
            JTextPane textoImprimir = new JTextPane();
            int contador_de_linhas = 1;
            String dado = Constantes.testos[2], linhas = Constantes.testos[2];
            String vetor [] = txtCodigo.getText().split(Constantes.testos[1]);
            for (String string : vetor) {
                linhas += contador_de_linhas + Constantes.testos[0] + string + Constantes.testos[1] ;
                contador_de_linhas ++;
            }
            for (int i = 0; i < 9; i++) {
                //if(!(Constantes.testos[8].equalsIgnoreCase(tblRegistos.getValueAt(tblRegistos.getRowCount() - 1, contador).toString()))){
                dado += tblRegistos.getValueAt(tblRegistos.getRowCount() - 1, i).toString() + Constantes.testos[0];
                //}
            }
            textoImprimir.setText(linhas + Constantes.testos[1] 
                    + Constantes.testos[1] + Constantes.testos[1] 
                    + Constantes.testos[7] + Constantes.testos[1] 
                    + dado + Constantes.textoLiceca);
            textoImprimir.print();
        } catch (PrinterException ex) {
            Logger.getLogger(MaqURM.class.getName()).log(Level.SEVERE, null, ex);
            //System.out.print(ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        new SobreSoftware(MaqURM.this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        new SobreProgramador(MaqURM.this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void tempoDeSimulacaoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tempoDeSimulacaoAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_tempoDeSimulacaoAncestorAdded

    private void tempoDeSimulacaoAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tempoDeSimulacaoAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tempoDeSimulacaoAncestorMoved

    private void tempoDeSimulacaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tempoDeSimulacaoStateChanged
        // TODO add your handling code here:
        valorExecucao.setText(Constantes.testos[0] + Constantes.testos[0] + tempoDeSimulacao.getValue());
    }//GEN-LAST:event_tempoDeSimulacaoStateChanged

    // função que compila o codigo fonte*/
    private boolean compilarCodigo() {
        //novaAreaDeSimulacao();
        analSint = new AnaliseSintatica();
        boolean compilado = analSint.analiseSintatica(txtCodigo.getText());
        txtMensagemConsola.setText(Constantes.testos[2]);
        for (Mensagem ms : analSint.msgList) {
            txtMensagemConsola.setText(txtMensagemConsola.getText() + (Constantes.testos[4] + ms.getLinha()) + Constantes.testos[5] + ms.getMensagem() + Constantes.testos[1]);
        }
        return compilado;
    }
    // função que executa o codigo depois de compilado

    private void executarCodigo(String codigo) {
        //txtMensagemConsola.setText(Constantes.testos[2]);
        btLimpar.setEnabled(false);
        interpreta = new Interpretador((DefaultTableModel) getTblRegistos().getModel());
        interpreta.ExecutarSimulacao(codigo, tempoDeSimulacao.getValue());
        pegaResultado();
        btLimpar.setEnabled(true);
    }
    // criador de nova tabela e limpa o editor

    private void novaSimulacao() {
        if (JOptionPane.showConfirmDialog(null, Constantes.msg[7], Constantes.msg[11], JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
            txtCodigo.setText(Constantes.template);
            novaAreaDeSimulacao();
        }
    }
    // actualizar o conteudo do ficheiro fonte

    private void guardarSimulacao() {
    }
    // gerar ficheiro com código fonte

    private void guardarComoSimulacao() {
        JFileChooser chooser = new JFileChooser();

        chooser.setApproveButtonText("Guardar");
        chooser.setFileFilter(new FileNameExtensionFilter(Constantes.testos[10], Constantes.testos[9]));
        chooser.showOpenDialog(null);
        ficheiro = chooser.getSelectedFile();

        try {
            String text = txtCodigo.getText();
            java.io.FileWriter fileWriter = new java.io.FileWriter(ficheiro + Constantes.testos[11]);
            try (java.io.BufferedWriter br = new java.io.BufferedWriter(fileWriter)) {
                br.write(text);
            }
        } catch (IOException ex) {
        }
    }
    // abrir um ficheiro anteriormente criado com a extenção .urm

    private void abrirSimulacao() {
        String linha, conteudo = Constantes.testos[2];
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter(Constantes.testos[10], Constantes.testos[9]));
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = fileChooser.showOpenDialog(this);
        if (result != JFileChooser.CANCEL_OPTION) {
            try {
                File fileName = fileChooser.getSelectedFile();
                if ((fileName == null) || (fileName.getName().equals(Constantes.testos[2]))) {
                    JOptionPane.showMessageDialog(this, "Nome invalido", "Verifica o ficheiro", JOptionPane.ERROR_MESSAGE);
                }
                is = new FileInputStream(fileName);
                InputStreamReader isr = new InputStreamReader(is);
                try (BufferedReader br = new BufferedReader(isr)) {
                    linha = br.readLine(); // primeira linha

                    // criar um carregando
                    while (linha != null) {
                        conteudo += linha + Constantes.testos[1];
                        linha = br.readLine();
                    }
                    // fechar o carregando
                    txtCodigo.setText(conteudo);
                }
            } // }
            catch (FileNotFoundException ex) {
                Logger.getLogger(MaqURM.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MaqURM.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        // } 
    }
    // gerar nova tabela

    private void novaAreaDeSimulacao() {
        tblRegistos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
                },
                new String[]{
                    Constantes.registo[0], Constantes.registo[1], Constantes.registo[2], Constantes.registo[3], Constantes.registo[4], Constantes.registo[5], Constantes.registo[6], Constantes.registo[7], Constantes.registo[8], Constantes.registo[9]
                }) {
                    Class[] types = new Class[]{
                        java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
                    };

                    @Override
                    public Class getColumnClass(int columnIndex) {
                        return types[columnIndex];
                    }
                });
    }
    // limpa tabela e recopera os favores iniciais

    private void limparTabelaResultado() {
        String[] dado = new String[9];
        for (int i = 0; i < 9; i++) {
            dado[i] = tblRegistos.getValueAt(0, i).toString();
        }
        tblRegistos.setModel(new DefaultTableModelImpl(
                new Object[][]{
                    {0, 0, 0, 0, 0, 0, 0, 0, 0}
                },
                new String[]{
                    Constantes.registo[0], Constantes.registo[1], Constantes.registo[2], Constantes.registo[3], Constantes.registo[4], Constantes.registo[5], Constantes.registo[6], Constantes.registo[7], Constantes.registo[8], Constantes.registo[9]
                }));
        for (int i = 0; i < 9; i++) {
            tblRegistos.setValueAt(dado[i], 0, i);
        }
        txtMensagemConsola.setText(Constantes.testos[2]);
    }
    // obter os valores da ultima linha da tabela de resultado

    private void pegaResultado() {
        String dado = Constantes.testos[2];
        for (int i = 0; i < 9; i++) {
            //if(!(Constantes.testos[8].equalsIgnoreCase(tblRegistos.getValueAt(tblRegistos.getRowCount() - 1, contador).toString()))){
            dado += tblRegistos.getValueAt(tblRegistos.getRowCount() - 1, i).toString() + Constantes.testos[0];
            //}
        }
        txtMensagemConsola.setText(Constantes.testos[7] + dado);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraFerramentas;
    private javax.swing.JButton btAbrir;
    private javax.swing.JButton btColar;
    private javax.swing.JButton btCopiar;
    private javax.swing.JButton btCortar;
    private javax.swing.JButton btGuardarComo;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSimular;
    private javax.swing.JSplitPane divisaoCodigoResultado;
    private javax.swing.JSplitPane divisaoTextTabela;
    private javax.swing.JLabel estencao;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JScrollPane ladoCodigo;
    private javax.swing.JScrollPane ladoRegistos;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuFincheiro;
    private javax.swing.JMenu menuSimular;
    private javax.swing.JScrollPane painelTexto;
    private javax.swing.JTable tblRegistos;
    private javax.swing.JSlider tempoDeSimulacao;
    private javax.swing.JTextPane txtCodigo;
    private javax.swing.JEditorPane txtMensagemConsola;
    private javax.swing.JLabel valorExecucao;
    private javax.swing.JScrollPane verMensagens;
    // End of variables declaration//GEN-END:variables

    private class DefaultTableModelImpl extends DefaultTableModel {

        public DefaultTableModelImpl(Object[][] data, Object[] columnNames) {
            super(data, columnNames);
        }
        Class[] types = new Class[]{
            java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
        };

        @Override
        public Class getColumnClass(int columnIndex) {
            return types[columnIndex];
        }
    }
    
    public static void main(String [] args) throws InterruptedException{
        Splash.getInstance().openSplash();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaqURM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Thread.sleep(3000);
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MaqURM().setVisible(true);
            }
        });
        Splash.getInstance().dispose();
    }
}
